### ISSUE TITLE
Update google.golang.org/protobuf version to fix CVE

### ISSUE THREAD

**Issue by jonathancampbell-wk** [grafana/rollout-operator#143]
The `google.golang.org/protobuf` version needs updated to 1.33 to fix the below CVE.

CVE: https://github.com/advisories/GHSA-8r3f-844c-mc37

**Comment by andyasp** [comment]
`google.golang.org/protobuf` was updated to `1.33` in #144. We'll cut a release with that included soon (likely early next week).
